resources:
- ../../base

namespace: app

images:
- name: us-central1-docker.pkg.dev/infra-exp-506709/images/app
  newName: us-central1-docker.pkg.dev/infra-exp-506709/images/app
  newTag: cc344a1207d55300d6f781dd0bea00c55821bced
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
